### ISSUE TITLE
Tree Transplant 1.0.9

### ISSUE THREAD

**Issue by LeonBlade** [StardewModders/mod-translations#13]
**[Tree Transplant](https://www.nexusmods.com/stardewvalley/mods/1342/)** lets you transplant trees (including fruit trees) on your farm without needing to chop them down and wait for them to regrow.

## Requested translations
See [default text](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Chinese](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/zh.json)~ (added thanks to @binxhlin!)
- [x] ~[French](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/fr.json)~ ([added](https://github.com/LeonBlade/TreeTransplant/pull/7) thanks to @The4thLaw!)
- [x] ~[German](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/de.json)~ (added thanks to @Firevulture!)
- [x] ~[Hungarian](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/hu.json)~ (added thanks to @therealmate)
- [x] ~[Italian](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/it.json)~ (added thanks to @xCarloC)
- [x] ~[Japanese](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/ja.json)~ ([added](https://github.com/LeonBlade/TreeTransplant/pull/10) thanks to @shirutan)
- [x] ~[Korean](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/ko.json)~ ([added](https://github.com/LeonBlade/TreeTransplant/issues/11) thanks to @overwritten!)
- [x] ~[Portuguese](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/pt.json)~ (added thanks to @Arcareon!)
- [x] ~[Russian](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/ru.json)~ ([added](https://github.com/LeonBlade/TreeTransplant/pull/6) thanks to @TheOzonO3!)
- [x] ~[Spanish](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/es.json)~ ([added](https://github.com/LeonBlade/TreeTransplant/pull/9) thanks to @Yllelder!)
- [x] ~[Turkish](https://github.com/LeonBlade/TreeTransplant/blob/master/TreeTransplant/i18n/tr.json)~ ([added](https://github.com/LeonBlade/TreeTransplant/issues/12) thanks to @cilekli-link!)

## Where translations appear in-game
* Robin's carpenter menu:
>![Tree Transplant](https://camo.githubusercontent.com/c53a7fb373e279426fcde4ebd33e9bc4f7319258/687474703a2f2f692e696d6775722e636f6d2f3733584437356a2e706e67)

* Transplant menu when selecting a tree:
>![Select a tree to transplant.](https://user-images.githubusercontent.com/635046/55107452-b8b2d900-50a7-11e9-8e25-34f7e4826db3.png)

* When picking a new location for a selected tree:
>![Choose a new spot for the tree.](https://user-images.githubusercontent.com/635046/55107501-e39d2d00-50a7-11e9-9c69-12a207de95ac.png)

* Invalid tree placement location:
>![Can't place here!](https://user-images.githubusercontent.com/635046/55107568-016a9200-50a8-11e9-9c37-139d45deaae4.png)

* Attempting to move a tree with a tap 
>*same notification as invalid tree placement*

## Credit
**TODO**

## See also
* [source code](https://github.com/LeonBlade/TreeTransplant)

**Comment by binxhlin** [comment]
This is Chinese translate.
Just rename ".json"
[zh.txt](https://github.com/StardewModders/mod-translations/files/3045855/zh.txt)

**Comment by LeonBlade** [comment]
@binxhlin Thank you!

**Comment by Arcareon** [comment]
Portuguese translate.
Just rename ".json"
[pt.txt](https://github.com/StardewModders/mod-translations/files/3095195/pt.txt)

**Comment by Firevulture** [comment]
[de.json.txt](https://github.com/StardewModders/mod-translations/files/3101274/de.json.txt)

German translation

**Comment by LeonBlade** [comment]
@Arcareon @Firevulture Thank you!

**Comment by overwritten** [comment]
Did the Korean translations! Just change it to a json file and you're good to go :') However, I'm not sure about the "InvalidCap" line (I'm not sure what tree tap is in Korean) so please have someone check that line in particular!!

[ko.txt](https://github.com/StardewModders/mod-translations/files/3312415/ko.txt)

**Comment by Pathoschild** [comment]
@overwritten If it helps, the game uses '수액 채취기' for tree tappers when Korean is selected.

**Comment by LeonBlade** [comment]
Thanks @overwritten newest release has Korean and Japanese languages.

**Comment by cilekli-link** [comment]
[tr.txt](https://github.com/StardewModders/mod-translations/files/3314354/tr.txt)

**Comment by xCarloC** [comment]
Hi, this is the italian translation:
[it.txt](https://github.com/StardewModders/mod-translations/files/4174667/it.txt)

**Comment by therealmate** [comment]
[hu.txt](https://github.com/StardewModders/mod-translations/files/4299252/hu.txt)

**Comment by Pathoschild** [comment]
@LeonBlade Two translations here for you. :)

**Comment by LeonBlade** [comment]
@Pathoschild Thanks for the ping!

**Comment by Pathoschild** [comment]
All translations complete. Thanks to all the translators! ❤️
