### ISSUE TITLE
Looking For Love

### ISSUE THREAD

**Issue by FoggyWizard** [StardewModders/mod-translations#45]
**[Looking For Love](https://www.nexusmods.com/stardewvalley/mods/10206)** Updated Siv's Marriage Mod. Makes an additional nine vanilla villagers available for marriage

## Requested translations
See [Looking for Love events and shared assets](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/i18n/default.json), [Clint Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Clint/default.json), [Gus Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Gus/default.json), [Lewis Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Lewis/default.json), [Linus Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Linus/default.json), [Marnie Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Marnie/default.json), [Pam Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Pam/default.json), [Sandy Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Sandy/default.json), [Willy Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Willy/default.json), [Wizard Dialogue](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Wizard/default.json), [Custom Companions Add-On](https://github.com/FoggyWizard/Looking-For-Love/tree/main/%5BCP%5D%20Looking%20for%20Love/%5BCC%5D%20Looking%20for%20Love/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [ ] Chinese (missing)
- [ ] French (missing)
- [ ] German (missing)
- [ ] Hungarian (missing)
- [ ] Italian (missing)
- [ ] Japanese (missing)
- [ ] Korean (missing)
- [ ] Portuguese (missing)
- [x] [Russian](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/i18n/ru.json) [1](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Clint/ru.json) [2](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Gus/ru.json) [3](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Lewis/ru.json) [4](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Linus/ru.json) [5](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Marnie/ru.json) [6](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Pam/ru.json) [7](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Sandy/ru.json) [8](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Willy/ru.json) [9](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Wizard/ru.json) [10](https://github.com/FoggyWizard/Looking-For-Love/tree/main/%5BCP%5D%20Looking%20for%20Love/%5BCC%5D%20Looking%20for%20Love/i18n/ru.json)~ (added thanks to @group 6squad!)
- [x] [Spanish](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/i18n/es.json) [1](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Clint/es.json) [2](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Gus/es.json) [3](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Lewis/es.json) [4](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Linus/es.json) [5](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Marnie/es.json)[6](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Pam/es.json) [7](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Sandy/es.json) [8](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Willy/es.json) [9](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Wizard/es.json) [10](https://github.com/FoggyWizard/Looking-For-Love/tree/main/%5BCP%5D%20Looking%20for%20Love/%5BCC%5D%20Looking%20for%20Love/i18n/es.json)~ (added thanks to @mardrest!)
- [ ] Turkish (missing)
- [x] [Thai](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/i18n/th.json) [1](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Clint/th.json) [2](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Gus/th.json) [3](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Lewis/th.json) [4](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Linus/th.json) [5](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Marnie/th.json) [6](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Pam/th.json) [7](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Sandy/th.json) [8](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Willy/th.json) [9](https://github.com/FoggyWizard/Looking-For-Love/blob/main/%5BCP%5D%20Looking%20for%20Love/%5BCP%5D%20Looking%20for%20Love/assets/Wizard/th.json) [10](https://github.com/FoggyWizard/Looking-For-Love/tree/main/%5BCP%5D%20Looking%20for%20Love/%5BCC%5D%20Looking%20for%20Love/i18n/th.json)~ added thanks to @ellipszist

## Where translations appear in-game
In dialogue and during events, along with some strings elsewhere. **Note, not just the i18n needs translating. In each character folder there is an additional default.json that needs translating. This effectively seperates the translation files into eight parts, one for general translations and one for each character.** Yes, I know it's tedious, but doing the dialogue files as language based includes was the best way to make it properly modular.

## Credit
**TODO**: I'll list translators in the Nexus credits. And probably the GitHub once I get around to making a readme for LfL

## See also
[Looking For Love](https://github.com/FoggyWizard/Looking-For-Love)

**Comment by seiji-48** [comment]
**`i`**

**Comment by mardrest** [comment]
Spanish translation is done by me and Russian translation by group 6squad.
[https://drive.google.com/file/d/1cTKMR8hMu88NpT3IVUuu9Fmjz5SLrPoK/view?usp=sharing](url)

**Comment by MagoSupremo123** [comment]
A Portuguese translation is available on nexus: https://www.nexusmods.com/stardewvalley/mods/18366

**Comment by 777PamPam777** [comment]
German Translation.

[de.json](https://github.com/StardewModders/mod-translations/files/15502325/de.json)

**Comment by Pathoschild** [comment]
There are translations pending an author response since 2024, so I'll close this ticket. Feel free to reopen it when you're available to handle contributions. Thanks to all the translators who submitted translations!
